In [3]:
import numpy as np
a=np.array([[1,2,3],[5,8,7]])
print("array created using passed list:\n",a)




array created using passed list:
 [[1 2 3]
 [5 8 7]]


In [9]:
b=np.zeros((3,4))
print("\n An array initialized with all zeros:\n",b)


 An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
c=np.full((3,3),6)
print("\n Array initialized with all :\n",c)




 Array initialized with all :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [29]:
d=np.random.random((2,2))
print("\n A random array \n",d)


 A random array 
 [[0.2719086  0.40715673]
 [0.49091843 0.86478046]]


In [31]:
e=np.arange(0,30,5)
print ("\n a sequential array with step of 5 \n",e) 


 a sequential array with step of 5 
 [ 0  5 10 15 20 25]


In [45]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
reshaped_arr=arr.reshape(4,3)
print(arr)
print(reshaped_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [47]:
fl_arr=arr.flatten()
print(arr)
print(fl_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [51]:
print(arr.ndim)

2


In [53]:
print(arr.shape)

(3, 4)


In [55]:
print(arr.size)

12


In [57]:
print(arr.dtype)

int32


In [59]:
c=arr.astype("f")
print(c)
b=arr.astype("i")
print(b)

[[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [8]:
  import numpy as np
  p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
  print(p[2:2])            

[]


In [9]:
print(p[3:3])

[]


In [10]:
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [1]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[1,14,15]])
print(p[3:3])

[]


In [2]:
print(p[2:2])

[]


In [3]:
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1 14 15]]
