In [3]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices(0,3),(1,2),(2,1),(3,0):\n",temp)


 Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [5]:
cond=arr>2
temp=arr[cond]
print("\nelements greater than 2:\n",temp)


elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr1,arr2)
print("\n joined arrays:\n",arr)

[1 2 3] [4 5 6]

 joined arrays:
 [1 2 3 4 5 6]


In [8]:
arr=np.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)


Horizontal joining:
 [1 2 3 4 5 6]


In [9]:
arr=np.vstack((arr1,arr2))
print("\n vertical joining:\n",arr)


 vertical joining:
 [[1 2 3]
 [4 5 6]]


In [10]:
arr=np.dstack((arr1,arr2))
print("\ndepth joining:\n",arr)


depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\n original array:\n",arr)
print("\n splitted array:\n", newarr)
print("\n splitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


 original array:
 [1 2 3 4 5 6]

 splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]

 splitted array in another form:

[1 2]
[3 4]
[5 6]


In [16]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("original array:\n",arr)

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -5.   6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [17]:
print("\nEvery other rows:\n",arr[0:3:2])


Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [18]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 column:\n",temp)


Array with first 2 rows and 3 column:
 [[-1.  2.  0.]
 [ 4. -5.  6.]]


In [19]:
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturn every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Return every other elements in the array:arr[::2]: [1 3 5 7]
